// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNPcFMzgYYEr-0gWTGoBM5aEh-H2ShpnY',
    appId: '1:698627793486:web:84e5ab13be896d9d81d91f',
    messagingSenderId: '698627793486',
    projectId: 'tcc-5ce43',
    authDomain: 'tcc-5ce43.firebaseapp.com',
    storageBucket: 'tcc-5ce43.appspot.com',
    measurementId: 'G-MV2V61JF3J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5yyx5nQ1JbxGHHyWpyHtUtcPnVhWCMgE',
    appId: '1:698627793486:android:2df1f456be5163a781d91f',
    messagingSenderId: '698627793486',
    projectId: 'tcc-5ce43',
    storageBucket: 'tcc-5ce43.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRjGB_XEAxwsy-vf8YRRzWnmKE6eb0TBY',
    appId: '1:698627793486:ios:ce1ede58ae34a0e381d91f',
    messagingSenderId: '698627793486',
    projectId: 'tcc-5ce43',
    storageBucket: 'tcc-5ce43.appspot.com',
    iosClientId: '698627793486-jhs9cef880v6ro2478j07nuinv5aqtrs.apps.googleusercontent.com',
    iosBundleId: 'com.example.tccApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRjGB_XEAxwsy-vf8YRRzWnmKE6eb0TBY',
    appId: '1:698627793486:ios:ce1ede58ae34a0e381d91f',
    messagingSenderId: '698627793486',
    projectId: 'tcc-5ce43',
    storageBucket: 'tcc-5ce43.appspot.com',
    iosClientId: '698627793486-jhs9cef880v6ro2478j07nuinv5aqtrs.apps.googleusercontent.com',
    iosBundleId: 'com.example.tccApp',
  );
}
